name: CI/CD Pipeline - NFL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Frontend - Build (React + Next.js)

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: client/nfl
        run: |
          npm install

      - name: Build the frontend
        working-directory: client/nfl
        run: |
          npm run build

  backend:
    runs-on: ubuntu-latest
    name: Backend - Build e Testes (Python Flask)

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" # ou a versão do Python que você está usando

      - name: Install dependencies
        working-directory: server
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        working-directory: server
        run: |
          . venv/bin/activate && pytest --maxfail=1 --disable-warnings -q > result.log; tail -n 10 result.log

      - name: Upload backend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: result.log
